/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "timer_clock.h"
#include "Timer.h"
#include "START_aliases.h"
#include "START.h"
#include "ADC_IN_aliases.h"
#include "ADC_IN.h"
#include "ADC.h"
#include "isr_10.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "LCD.h"
#include "UART.h"
#include "Timer2.h"
#include "Trigger_aliases.h"
#include "Trigger.h"
#include "Trigger_out.h"
#include "echo_aliases.h"
#include "echo.h"
#include "In1_aliases.h"
#include "In1.h"
#include "In0_aliases.h"
#include "In0.h"
#include "reloj1.h"
#include "enable_aliases.h"
#include "enable.h"
#include "T1.h"
#include "EnableTimer3.h"
#include "Timer3.h"
#include "ResetTimer3.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

